### ISSUE TITLE
Missing .smi assets?

### ISSUE THREAD

**Issue by dillon-zephyrai** [ashvardanian/usearch-molecules#1]
Hi, I've gotten the `example` database to work and I can perform searches on `pubchem` using a raw index object. However in `pubchem` I cannot match the results to their smiles representations -- `FingerprintedDataset` is expecting to find `.smi` files, but afaics these are only included with `example`. Am I missing something?

**Comment by ashvardanian** [comment]
Those files are redundant so I don't upload them for most datasets. To re-generate them, please run the `prep_smiles.py` script.

Let me know if it works 🤗

**Comment by dillon-zephyrai** [comment]
Thank you! Some minor edits needed to `prep_smiles.py` but it's working now.

**Comment by ashvardanian** [comment]
Epic, @dillon-zephyrai! Feel free to submit a patch 🤗
