### ISSUE TITLE
Trying the search for user-defined sets

### ISSUE THREAD

**Issue by Ljohn89** [ashvardanian/usearch-molecules#2]
Hello @ashvardanian,
I'm working on implementing the Usearch algorithm for around 300 million molecules, following the steps outlined in your post. However, the search program is currently taking too long to identify and display results. I'm seeking guidance on approaches to optimize the program for faster execution, aiming for results in milliseconds. Any pointers or suggestions would be appreciated.

The snippet of the search code is mentioned below, 
#################################################################
from usearch_molecules.dataset import FingerprintedDataset, shape_mixed

data = FingerprintedDataset.open("data/example", shape=shape_mixed)

# No inspiration? Pick a random molecule with `data.random_smiles()`
results = data.search('CC(O)C(CN)=NNCC(C)(C)C', 100)

results_keys = [r[0] for r in results]
results_smiles = [r[1] for r in results]
results_scores = [r[2] for r in results]
##################################################################

Regards,
Lijo

**Comment by ashvardanian** [comment]
Hi @Ljohn89! Sorry, I didn't see the issue earlier. How slow is the search? What hardware are you running on right now?
