### ISSUE TITLE
[Enamine REAL] search and clustering indexes

### ISSUE THREAD

**Issue by lebrat** [ashvardanian/usearch-molecules#7]
Hi Ash,

Thank you once again for your excellent work. I would like to request access to the search and clustering indexes for the Enamine Real dataset. Please feel free to reach out to me directly at leo.lebrat@gmail.com.

Best regards,
Leo

**Comment by pavank** [comment]
Hi Ash, I want to jump in on this thread and request the same. Can you please reach me at pavan.keerthi@gmail.com
